app: matrix-cloud
service: matrix-cloud-blockchain-event-handler-service
ports:
  - port: 9090
    targetPort: 9090
    name: grpc
metrics:
  scrape: false
  path: /metrics/prometheus
hpa: true
serviceAccountName: aws-access
deploy:
  image: 316274061697.dkr.ecr.ap-northeast-1.amazonaws.com
  stage:
    alpha:
      cluster: matrix-alpha
      namespace: alpha
      autoSync: true
    alpha-testnet:
      cluster: matrix-alpha
      namespace: alpha-testnet
      autoSync: true
    beta:
      cluster: matrix-beta
      namespace: beta
    beta-testnet:
      cluster: matrix-beta
      namespace: beta-testnet
    prod-mainnet:
      cluster: matrix-prod
      namespace: prod-mainnet
    prod:
      cluster: matrix-prod
      namespace: prod