dynamodb:
  token-table-name: matrix-cloud-token-alpha-mainnet
  ethereum-event-table-name: matrix-cloud-ethereum-event-alpha
grpc:
  client:
    matrix-cloud-marketplace-metadata-service:
      address: 'static://localhost:9094'
      negotiationType: 'PLAINTEXT'
    matrix-cloud-blockchain-event-handler-service:
      address: 'static://localhost:9095'
      negotiationType: 'PLAINTEXT'
