spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      bootstrap:
        servers: ${kafka_prod_url}
      sasl:
        mechanism: AWS_MSK_IAM
        jaas.config: software.amazon.msk.auth.iam.IAMLoginModule   required;
        client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler