spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.amazonaws.services.schemaregistry.serializers.GlueSchemaRegistryKafkaSerializer
      properties:
        region: ap-northeast-1
        max.request.size: 8388608
        dataFormat: AVRO
        schemaAutoRegistrationEnabled: true
    
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.amazonaws.services.schemaregistry.deserializers.GlueSchemaRegistryKafkaDeserializer
      properties:
        region: ap-northeast-1
        specific.avro.reader: true
        fetch.message.max:.bytes: 8388608
        dataFormat: AVRO
        avroRecordType: SPECIFIC_RECORD

topics:
  rinkeby-event-log-topic:
    name: rinkeby-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  ethereum-event-log-topic:
    name: ethereum-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  mumbai-event-log-topic:
    name: mumbai-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  polygon-event-log-topic:
    name: polygon-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  flow-test-net-event-log-topic:
    name: flow-test-net-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  flow-main-net-event-log-topic:
    name: flow-main-net-blockchain-event-log-${STAGE:local}
    replicas: 1
    partitions: 1
  flow-test-net-transaction-topic:
    name: flow-test-net-blockchain-transaction-${STAGE:local}
    replicas: 1
    partitions: 1
    max.request.size: 8388608
  flow-main-net-transaction-topic:
    name: flow-main-net-blockchain-transaction-${STAGE:local}
    replicas: 1
    partitions: 1
    max.request.size: 8388608
  flow-main-net-transaction-history-topic:
    name: flow-main-net-blockchain-transaction-history-${STAGE:local}
    replicas: 1
    partitions: 1
    max.request.size: 8388608
  flow-converted-events-topic:
    name: flow-converted-events-${STAGE:local}
    replicas: 1
    partitions: 1
  flow-converted-events-history-topic:
    name: flow-converted-events-history-${STAGE:local}
    replicas: 1
    partitions: 1
