app: matrix-cloud
service: matrix-cloud-blockchain-syncer
ports:
  - port: 9090
    targetPort: 9090
    name: grpc
metrics:
  scrape: true
  path: /metrics/prometheus
hpa: false
serviceAccountName: aws-access
deploy:
  image: 316274061697.dkr.ecr.ap-northeast-1.amazonaws.com
  stage:
    alpha:
      cluster: matrix-alpha
      namespace: alpha
      autoSync: true
    beta:
      cluster: matrix-beta
      namespace: beta
    prod:
      cluster: matrix-prod
      namespace: prod