blockchain:
  rinkeby-provider-endpoint:
    - ${rinkeby-provider-endpoint}
  ethereum-provider-endpoint:
    - ${ethereum-provider-endpoint}
  mumbai-provider-endpoint:
    - ${mumbai-provider-endpoint}
  polygon-provider-endpoint:
    - ${polygon-provider-endpoint}
cloudfrontUrl: ${cloudfrontUrl}
spring:
  redis:
    host: ${redis_url_alpha}
    port: 6379
    password: ${redis_password_alpha}
    database: 0