blockchain:
  ethereum-provider-endpoint:
    - https://eth-mainnet.g.alchemy.com/v2/yoJCyg5XsbdD9u072GIASQJqNNYdpJlW
  mumbai-provider-endpoint:
    - https://polygon-mumbai.g.alchemy.com/v2/AaK0qSuDMI4PT_9VFm4aa1IL1aYecJmT
  polygon-provider-endpoint:
    - https://polygon-mainnet.g.alchemy.com/v2/LAVH4Qsdw9CiY0VsTJZiztl1IQCJKt5D
cloudfrontUrl: https://dj2mwotxs0n3u.cloudfront.net
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
grpc:
  client:
    matrix-cloud-flow-service:
      address: 'static://localhost:9091'
      negotiationType: 'PLAINTEXT'
    marketplace-flow-service:
      address: 'static://localhost:9092'
      negotiationType: 'PLAINTEXT'