blockchain:
  ethereum-provider-endpoint:
    - ${ethereum-provider-endpoint}
  mumbai-provider-endpoint:
    - ${mumbai-provider-endpoint}
  polygon-provider-endpoint:
    - ${polygon-provider-endpoint}
cloudfrontUrl: https://{your-cloud-front-url}
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
grpc:
  client:
    matrix-cloud-flow-service:
      address: 'static://localhost:9091'
      negotiationType: 'PLAINTEXT'
    marketplace-flow-service:
      address: 'static://localhost:9092'
      negotiationType: 'PLAINTEXT'