blockchain:
  ethereum-provider-endpoint:
    - "https://eth-mainnet.g.alchemy.com/v2/yoJCyg5XsbdD9u072GIASQJqNNYdpJlW"
  bsc-provider-endpoint:
    - "https://bsc-mainnet.nodereal.io/v1/b5f5cdae32334b158dbbdb3f62c2c0a3"
  polygon-provider-endpoint:
    - "https://polygon-mainnet.g.alchemy.com/v2/LAVH4Qsdw9CiY0VsTJZiztl1IQCJKt5D"
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
grpc:
  client:
    matrix-cloud-flow-service:
      address: 'static://localhost:9091'
      negotiationType: 'PLAINTEXT'
    marketplace-flow-service:
      address: 'static://localhost:9092'
      negotiationType: 'PLAINTEXT'