grpc:
  server:
    port: 9090
spring:
  application:
    name: chainsync-blockchain-syncer
  profiles:
    active: ${STAGE:local}
    include: flow-event-fetcher-grpc, metrics, flow-service-grpc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
dynamodb:
  bsc-event-table-name: chainsync-bsc-event-${STAGE:local}
  ethereum-event-table-name: chainsync-ethereum-event-${STAGE:local}
  polygon-event-table-name: chainsync-polygon-event-${STAGE:local}
  bsc-transaction-table-name: chainsync-bsc-transaction-${STAGE:local}
  eth-transaction-table-name: chainsync-eth-transaction-${STAGE:local}
  polygon-transaction-table-name: chainsync-polygon-transaction-${STAGE:local}
  blockchain-tip-table-name: chainsync-blockchain-tip-${STAGE:local}
  sync-error-table-name: chainsync-blockchain-sync-error-${STAGE:local}
  blockchain-offset-table-name: chainsync-blockchain-offset-${STAGE:local}
  block-success-table-name: chainsync-block-success
  block-failed-table-name: chainsync-block-failed-${STAGE:local}
  block-info-table-name: chainsync-etl-ethereum-block-info-${STAGE:local}

cloud:
  aws:
    region:
      static: ap-northeast-1
s3:
  bucket: marketplace-blockchain-${STAGE:local}
  event:
    flow:
      bucket: marketplace-event-fetcher
