phantaBear:
  address: "0xA9D29DB8B0A2e87482B7D2EaD732aaf161dAC3D9"
phancyPet:
  address: "0x554478E4c47EF61806fab268d1B74543d4D01f91"
topics:
  rinkeby-event-log-topic:
    name: rinkeby-blockchain-event-log-alpha
  mumbai-event-log-topic:
    name: mumbai-blockchain-event-log-alpha
  ethereum-event-log-topic:
    name: ethereum-blockchain-event-log-alpha
  polygon-event-log-topic:
    name: polygon-blockchain-event-log-alpha