phantaBear:
  address: "0x67d9417c9c3c250f61a83c7e8658dac487b56b09"
phancyPet:
  address: "0x1eFcFA6055F782a9c6d5091e9Fa1E5a673574AD3"
topics:
  rinkeby-event-log-topic:
    name: rinkeby-blockchain-event-log-prod
  mumbai-event-log-topic:
    name: mumbai-blockchain-event-log-prod
  ethereum-event-log-topic:
    name: ethereum-blockchain-event-log-prod
  polygon-event-log-topic:
    name: polygon-blockchain-event-log-prod
