grpc:
  client:
    matrix-cloud-blockchain-syncer:
      address: 'static://chainsync-blockchain-syncer:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
