grpc:
  server:
    port: 9090
spring:
  main:
    web-application-type: none
  profiles:
    active: ${STAGE:local}
    include: theirsverse-grpc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    consumer:
      group-id: chainsync-blockchain-event-handler-service-${STAGE:local}
dynamodb:
  nft-collection-name: chainsync-nft-collection-${STAGE:local}
  blockchain-contract-template-table-name: chainsync-blockchain-contract-template-${STAGE:local}
  token-table-name: chainsync-token-${STAGE:local}
