grpc:
  client:
    matrix-cloud-flow-service:
      address: 'static://chainsync-flow-service:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    marketplace-flow-service:
      address: 'static://marketplace-flow-service:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
